name: measurements_repository
description: Repository responsible for handling user fitness entries
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  database_client:
    path: ../database_client
  equatable: ^2.0.3
  rxdart: ^0.27.4
  steps_client:
    path: ../steps_client

dev_dependencies:
  test: ^1.19.2
